---
- name: Baseline Configuration
  hosts: all
  user: root
  roles:
    - role: base

- name: Apache
  hosts: apache
  user: root
  roles:
    - role: apache

# - name: Postgresql
#   hosts: postgres
#   user: root
#   roles:
#     - role: postgres